name: mesh-boolean
channels:
    - conda-forge
dependencies:
  - python=3.7
  - python.app
  - boost
  - eigen
  - pybind11
  - cmake>=3.14
  - git
  - pip>=19.0
  - COMPAS>=0.15.6
  - PySide2
  - PyOpenGL
  - pip:
      - git+https://github.com/blockresearchgroup/compas_libigl.git#egg=compas_libigl
      - git+https://github.com/compas-dev/compas_viewers.git#egg=compas_viewers
