name: build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-packages:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - uses: conda-incubator/setup-miniconda@v2.0.0
        with:
          miniconda-version: "latest"
          auto-activate-base: true

      - name: Generate testing script
        run: |
          python test.py

      - name: Run test script
        run: |
          test.bat
