name: test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - uses: conda-incubator/setup-miniconda@v2.0.0
        with:
          miniconda-version: "latest"
          auto-activate-base: true

      - name: Generate testing script
        run: |
          python test.py

      - name: Run test script Win
        if: runner.os == 'Windows'
        run: |
          temp\test.windows.bat

      - name: Run test script Mac
        if: runner.os == 'macOS'
        run: |
          chmod +x "temp/test.sh"
          temp/test.macos.sh

      - name: Run test script Linux
        if: runner.os == 'Linux'
        run: |
          chmod +x "temp/test.sh"
          temp/test.linux.sh

  post-test:
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: update tested record
        run: |
          python post-test.py
          cat tested.json

      - uses: EndBug/add-and-commit@v7
        with:
          add: 'tested.json'